name: Python CD

on:
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: lambda-bundle
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        aws-region: ${{ vars.REGION }}
        role-to-assume: ${{ vars.OIDC_ROLE }}
        role-session-name: IAM-Github-Actions-TF
    
    - name: Deploy to AWS
      run: |
        aws lambda update-function-code --function-name ${{ vars.LAMBDA_FUNCTION_NAME }} --zip-file fileb://lambda_function.zip
